before_script:
  - echo -e 'ssh -o "StrictHostKeyChecking no" git@github.com'
language: objective-c
xcode_workspace: Digipost.xcworkspace # path to your xcodeproj folder
xcode_scheme: Digipost-Enterprise
