
var target = UIATarget.localTarget();
target.frontMostApp().mainWindow().tableViews()[0].tapWithOptions({tapOffset:{x:0.39, y:0.03}});
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().mainWindow().tableViews()[0].dragInsideWithOptions({startOffset:{x:0.93, y:0.54}, endOffset:{x:0.93, y:0.39}, duration:1.1});
target.frontMostApp().mainWindow().tableViews()[0].tapWithOptions({tapOffset:{x:0.41, y:0.39}});
target.frontMostApp().keyboard().keys()["Delete"].tap();
target.frontMostApp().mainWindow().collectionViews()[0].cells()[8].images()["Trophy"].tapWithOptions({tapOffset:{x:0.22, y:0.51}});
target.frontMostApp().navigationBar().buttons()["Lagre"].tap();
target.delay(5);
target.frontMostApp().navigationBar().leftButton().tap();
target.frontMostApp().mainWindow().tableViews()[0].tapWithOptions({tapOffset:{x:0.41, y:0.07}});
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().mainWindow().tableViews()[0].tapWithOptions({tapOffset:{x:0.33, y:0.37}});
target.frontMostApp().mainWindow().collectionViews()[0].cells()[0].images()["Folder"].tapWithOptions({tapOffset:{x:0.66, y:0.61}});
target.frontMostApp().keyboard().typeString("n");
target.frontMostApp().navigationBar().buttons()["Lagre"].tap();
target.delay(5);
target.frontMostApp().navigationBar().rightButton().tap();
target.frontMostApp().navigationBar().tapWithOptions({tapOffset:{x:0.11, y:0.50}});
